name: Auto-Update Chess Leaderboard

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run API Extraction Script
        env:
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
        run: python fetch_data.py

      - name: Commit and Push new JSON
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add leaderboard.json
         
          git commit -m "Auto-update leaderboard data" || echo "No changes to commit"
          git push
